package prestamo.modelo;
// Generated 4/04/2018 06:12:32 PM by Hibernate Tools 4.3.1



/**
 * Socios generated by hbm2java
 */
public class Socios  implements java.io.Serializable {


     private int id;
     private String nombreSocio;
     private Float tasaInteres;
     private Float montoSocio;

    public Socios() {
    }

	
    public Socios(int id) {
        this.id = id;
    }
    public Socios(int id, String nombreSocio, Float tasaInteres, Float montoSocio) {
       this.id = id;
       this.nombreSocio = nombreSocio;
       this.tasaInteres = tasaInteres;
       this.montoSocio = montoSocio;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreSocio() {
        return this.nombreSocio;
    }
    
    public void setNombreSocio(String nombreSocio) {
        this.nombreSocio = nombreSocio;
    }
    public Float getTasaInteres() {
        return this.tasaInteres;
    }
    
    public void setTasaInteres(Float tasaInteres) {
        this.tasaInteres = tasaInteres;
    }
    public Float getMontoSocio() {
        return this.montoSocio;
    }
    
    public void setMontoSocio(Float montoSocio) {
        this.montoSocio = montoSocio;
    }




}


